swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: 0.0.1
  title: Framework Demo App
  description: A demo app for framework with lovely types

################################################################################
#             Host, Base Path, Schemes, Content Types and Security             #
################################################################################
host: example.com
basePath: /demo
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

################################################################################
#                                  Paths                                       #
################################################################################
paths:
  /test2/{segmentId}:
    post:
      description: A test route
